import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-activities-data',
  templateUrl: './activities-data.component.html',
  styleUrls: ['./activities-data.component.css']
})
export class ActivitiesDataComponent implements OnInit {

  constructor() {}

  ngOnInit(): void {}
  TableData: any[] = [
    {
      type: 'T',
      status: 'red',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'T',
      status: 'yellow',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'T',
      status: 'lightblue',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'T',
      status: 'black',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'O',
      status: 'red',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'O',
      status: 'red',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'O',
      status: 'red',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'O',
      status: 'yellow',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'O',
      status: 'yellow',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'O',
      status: 'blue',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'N',
      status: '',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
    {
      type: 'D',
      status: '',
      description: 'Do Something',
      owner: 'John',
      dueDate: '1/22/2021',
      priority: 'MEDIUM',
      author: 'Smith',
      dateCreated: '6/8/2022',
      comments: 'fhr',
    },
  ];

}
